import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'


import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import About from './About'
import Contact from './Contact'
import Hero from './Hero'
import Skills from './Skills'
import Works from './Work'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      {/* Hero Section */}
      <Hero />
      {/* About Section */}
      <About />
      {/* Skills Section */}
      <Skills />
      {/* Works Section */}
      <Works />
      {/* Contact */}
      <Contact />
      {/* footer */}
      <Footer />
    </div>
  )
}
